
mayeco_post_list:
    path:     /
    defaults: { _controller: MayecoPostBundle:Default:list }

mayeco_post_single:
    path:     /{id}
    defaults: { _controller: MayecoPostBundle:Default:single }
