
mayeco_post_list:
    path:     /
    defaults: { _controller: MayecoPostBundle:Post:list }
    methods:  [GET]

mayeco_post_single:
    path:     /ver-post/{id}
    defaults: { _controller: MayecoPostBundle:Post:single }
    methods:  [GET]
    requirements:
        id: \d+
