
mayeco_post_list:
    path:     /{page}
    defaults: { _controller: MayecoPostBundle:Post:list, page: 1 }

mayeco_post_single:
    path:     /ver-post/{id}
    defaults: { _controller: MayecoPostBundle:Post:single }
